version: '3.1'

services:
  mariadb:
    image: mariadb:10
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: discuss


  caddy:
    image: caddy:2-alpine
    ports:
    - 8080:8080
    volumes:
    - ./Caddyfile:/etc/caddy/Caddyfile
